name: Restart HF space

on:
  push:
    branches:
      - main

jobs:
  restart_hf_space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install huggingface-hub

      - name: Run script
        run: python scripts/restart_hf_space.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
