name: Restart Dana Space

on:
  push:
    branches:
      - main

jobs:
  restart_hf_space:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r dana_client/requirements.txt

      - name: Run script
        run: python dana_client/restart_dana.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
