name: Benchmark ROCm (Nightly Transformers)

on:
  workflow_dispatch:
  schedule:
    # every three hours
    - cron: "0 */3 * * *"

jobs:
  benchmark_rocm_nightly:
    runs-on: hf-amd-mi210-dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Optimum-Benchmark and Optimum-AMD
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://github.com/huggingface/optimum-benchmark
          git clone https://github.com/huggingface/optimum-amd
        env:
          PAT: ${{ secrets.PAT }}

      - name: Build image
        run: docker build
          --file optimum-benchmark/docker/rocm.dockerfile
          --build-arg USER_ID=$(id -u)
          --build-arg GROUP_ID=$(id -g)
          --build-arg ROCM_VERSION=5.6.1
          --tag opt-bench-rocm:5.6.1
          .

      - name: Run Benchmarks
        run: docker run
          --rm
          --device /dev/kfd
          --device /dev/dri
          --entrypoint /bin/bash
          --volume $(pwd):/workspace/optimum-dana
          --volume $HOME/.cache/huggingface:/home/user/.cache/huggingface
          --workdir /workspace/optimum-dana
          --env USE_ROCM="1"
          --env HF_TOKEN=${{ secrets.HF_TOKEN }}
          --env USERNAME=${{ secrets.USERNAME }}
          --env PASSWORD=${{ secrets.PASSWORD }}
          --env BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}
          opt-bench-rocm:5.6.1
          -c "cd optimum-benchmark && pip install -e .[peft,diffusers] && cd .. && sh benchmarks/rocm_nightly.sh"
